In [4]:
#numpy is used for work with arrays arrays in nympy are ndarray
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr) 

#to create nd array we can pass in a list, tuple or any array-like object into the array() method
arr1 = np.array((1,4,5,2,7,8))
print(arr1)

#2d and 3d array are

arr2 = np.array([[1,2,3],[7,8,9]])
print('2d array example', arr2)
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print('3d array example', arr3)

print(arr.ndim)
print(arr2.ndim)
print(arr3.ndim)

#while creating an array you can define its dim
array = np.array([1,2,3,4,5],ndmin=5)
print(array.ndim)

#we can acess the array elements and do calculations on them 
print(arr[2]+arr[3])

[1 2 3 4 5 6]
[1 4 5 2 7 8]
2d array example [[1 2 3]
 [7 8 9]]
3d array example [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
1
2
3
5
7


In [5]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [ ]:

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])


[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


In [10]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])
print(arr[0:2, 2])#from both element return index 2
print(arr[0:2, 1:4])



[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [11]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr.dtype)

arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

int64
<U6


In [17]:
#defining datatype while forming array
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)
print("\n")
#change the datatype from float to int
#astype() function creates a copy of the array, and allows you to specify the data type as a parameter.
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

print("\n")
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)


[b'1' b'2' b'3' b'4']
|S1
[1 2 3 4]
int32


[1 2 3]
int64


[ True False  True]
bool


In [27]:
#copy 
'''
difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.
copy owns the data and any changes made to the copy will not affect original array, 
and any changes made to the original array will not affect the copy.
'''
arr = np.array([1,2,3,4,5,7,8,])
x = arr.copy()
arr[0] = 42 

print("orignal array :" , arr)
print("copy of an orignal array :" , x)


arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
y = arr.copy()
x[0] = 31

print("orignal array :" , arr)
print("view of an origanl array :" , x)

print("To check if the copy owns the the data and view does not The copy returns None , The view returns the original array.")
print(x.base)#it will refers to orignal data as does not owns the data
print(y.base)#it will return none as owns the data





orignal array : [42  2  3  4  5  7  8]
copy of an orignal array : [1 2 3 4 5 7 8]
orignal array : [31  2  3  4  5]
view of an origanl array : [31  2  3  4  5]
To check if the copy owns the the data and view does not The copy returns None , The view returns the original array.
[31  2  3  4  5]
None


In [30]:
#shape Function
import numpy as np
'''
(2, 4), which means that the array has 2 dimensions, where the 
first dimension has 2 elements and the second has 4.
'''
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)
print("\n")
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('shape of array :', arr.shape)


(2, 4)


[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [ ]:
#reshape function
#changing the shape of the array
#reshaping can add or remove dimension or number of elements from the array

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

print("\n")
newarr = arr.reshape(2, 3, 2)
print(newarr)

print("\n")
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base)#it is veiw

print("\n")
#unkown dimension rshaping
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)#pass -1 as the value, and NumPy will calculate this number for you.
print(newarr)

print("\n")
#converting multidimensional array to one dimensional (flattening the array)
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print("Unflattened :", arr)
print("flattened : ",newarr)




[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


[1 2 3 4 5 6 7 8]


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Unflattened : [[1 2 3]
 [4 5 6]]
flattened :  [1 2 3 4 5 6]
[1 2 3 4 5 6]


In [ ]:
#iteration of the array acessing each element from the array and visiting it
import numpy as np
arr = np.array([1, 2, 3])
for x in arr:
  print(x)
  
print("\n")
#2d Array
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
    for y in x:
        print(y)
        
print("\n")
#3d Array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)
            


1
2
3


1
2
3
4
5
6


1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8


In [50]:
#iterating with nditer 
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
    print(x)
    
arr = np.array([1, 2, 3])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)
  
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:, ::2]):
  print(x)
  
#Enumerated Iteration Using ndenumerate()
import numpy as np
arr = np.array([1, 2, 3])
for idx, x in np.ndenumerate(arr):
  print(idx, x)
  
print("\n")
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

1
2
3
4
5
6
7
8
np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
1
3
5
7
(0,) 1
(1,) 2
(2,) 3


(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
