In [4]:
#numpy is used for work with arrays arrays in nympy are ndarray
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr) 

#to create nd array we can pass in a list, tuple or any array-like object into the array() method
arr1 = np.array((1,4,5,2,7,8))
print(arr1)

#2d and 3d array are

arr2 = np.array([[1,2,3],[7,8,9]])
print('2d array example', arr2)
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print('3d array example', arr3)

print(arr.ndim)
print(arr2.ndim)
print(arr3.ndim)

#while creating an array you can define its dim
array = np.array([1,2,3,4,5],ndmin=5)
print(array.ndim)

#we can acess the array elements and do calculations on them 
print(arr[2]+arr[3])

[1 2 3 4 5 6]
[1 4 5 2 7 8]
2d array example [[1 2 3]
 [7 8 9]]
3d array example [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
1
2
3
5
7


In [5]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])






[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
